# Generated by Django 5.1.3 on 2024-11-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='IN_PROGRESS', max_length=20),
        ),
    ]
